FROM tomcat:10.1-jdk17-temurin
RUN rm -rf /usr/local/tomcat/webapps/*
RUN mkdir -p /usr/local/tomcat/webapps/ROOT && printf 'ok' > /usr/local/tomcat/webapps/ROOT/index.html
COPY artifacts/catalog-service.war /usr/local/tomcat/webapps/catalog-service.war
EXPOSE 8080
CMD ["catalina.sh", "run"]
